SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D, SKILLCODES S_PYTHON, SKILLCODES S_CSHARP
WHERE S_PYTHON.NAME = 'Python'
  AND S_CSHARP.NAME = 'C#'
  AND ((D.SKILL_CODE & S_PYTHON.CODE) != 0
  OR (D.SKILL_CODE & S_CSHARP.CODE) != 0)
ORDER BY D.ID ASC;
