-- 조건에 맞는 사용자와 총 거래금액 조회하기

SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B JOIN USED_GOODS_USER U ON B.WRITER_ID=U.USER_ID
WHERE STATUS='DONE'
GROUP BY USER_ID
HAVING TOTAL_SALES>=700000
ORDER BY 3
