-- 업그레이드 된 아이템 구하기
-- PARENT_ITEM_ID가 RARE에 속하는 행을 추출
SELECT I.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO I JOIN ITEM_TREE T ON I.ITEM_ID=T.ITEM_ID
WHERE PARENT_ITEM_ID IN (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE')
ORDER BY ITEM_ID DESC;