-- 업그레이드 된 아이템 구하기
-- 서브쿼리를 통해 RARE인 아이템의 ITEM_ID를 PARENT_ITEM_ID를 연결해주기

SELECT A.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO AS A
LEFT OUTER JOIN ITEM_TREE AS B
ON A.ITEM_ID = B.ITEM_ID
WHERE B.PARENT_ITEM_ID IN(
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE')
ORDER BY A.ITEM_ID DESC
